### ISSUE TITLE
Does this design not take into account the installation of the fan in the electronics compartment?

### ISSUE THREAD

**Issue by poloniumn** [FrankenVoron/DoomCube-2#11]
This is a very nice design, I really like it, but I downloaded and checked the CAD model and found that the skirt is not designed with a fan, how is the cooling of the motherboard done? Install the fan directly on the motherboard?

**Comment by hartk1213** [comment]
currently there isnt an official fan mount in the skirts, i just have a fan stuck with vhb tape blowing on the drivers ...i want to eventually install a blower fan up there i just havent gotten around to it

**Comment by poloniumn** [comment]
Thank you.

Looks like I can print a motherboard fan bracket internally to dissipate the heat, which isn't difficult


One more small question, will there be any other changes in the near future, I'm going to start upgrading my voron, I don't want it to become obsolete in the middle of production

**Comment by poloniumn** [comment]
One more question, I noticed that the machine does not have an exhaust like voron, he is a completely closed machine? How to solve the unpleasant smell of ABS?

**Comment by hartk1213** [comment]
Never more micro is what I have installed in mine to deal with smell
